### ISSUE TITLE
Not working with Allure2?

### ISSUE THREAD

**Issue by cyborghound** [fhoeben/allure-fitnesse-listener#5]
Hi F. Hoeben,

I am trying to build a setup with Jenkins and your Fitnesse / HSAC setup in combination with the Allure listener. My project uses mvn clean test-compile and then downloads everything and runs the tests.

I included the sample pom.xml content from the listener into the pom.xml from the fitnesse hsac git clone. I also installed the Allure plugin for Jenkins so I would have a dashboard in Jenkins. And updated the versions from the sample.xml to the newest ones.

Eventually what I do is run mvn clean test-compile -Pallure and I can see that allure is being download and a zip is generated. The only problem I have is that the results in this zip are always empty. And therefore also in the Jenkins Allure dashboard.

Is there something I did wrong or did I missed something? Eventually I want to first build the project and then test it in another stage from a pipeline, but I did not get the maven code to work were prompts pop up and found out the command line rule above also installs everything. I will add specific test scenario's later in the maven command line, but first want this to work.

I hope you have the answer to my empty results. Thanks!

**Comment by fhoeben** [comment]
I'm not a real expert on Allure, as I don't use it myself.
But do I get correctly you are using allure 2? The latest release of this project is based on Allure 1. I did make a branch as initial setup for Allure 2.

For running with allure I recommend you check out the [allure](https://github.com/fhoeben/sample-fitnesse-project/tree/allure) (or [allure2](https://github.com/fhoeben/sample-fitnesse-project/tree/allure2)) branch of the sample project. That should get you started pom/project wise.

If you only target 'test-compile' you will never have test results. The FitNesse tests are run as 'integration tests' so you should either use `mvn clean verify -P allure`, or `mvn clean test-compile failsafe:integration-test -P allure`

**Comment by tcnh** [comment]
If you use the allure profiles as-is, you'll get a directory target/allure-results (containing xml per test case and all attachments). My guess is that's the folder the allure jenkins plugin should pick up and create the report from?

Alternatively: after allure-results are generated, run mvn site -Pallure to generate target/allure-report. This directory contains the Allure report.
I then use HTMLPublisher in Jenkins to publish the allure report and attach it to my builds.  (Be sure to check hudson.model.DirectoryBrowserSupport.CSP rules, because the allure report is quite JS-heavy)

Will have a look at the allure-plugin though.

**Comment by cyborghound** [comment]
Thanks all, I tried the sample project and found the following problem in the build.

[ERROR] Failed to execute goal on project sample-fitnesse-project-using-hsac-fixtures: Could not resolve dependencies for project nl.hsac:sample-fitnesse-project-using-hsac-fixtures:jar:1.0-SNAPSHOT: Could not find artifact nl.hsac:allure-fitnesse-listener:jar:2.0.0-SNAPSHOT -> [Help 1]

I thin this has to do with the fact that 2.0.0-SNAPSHOT is not a version in the nl.hsac maven repository. I did use mvn clean test-compile failsafe:integration-test -P allure on the sample project allure2 branch.

I also tried to use the sample project with branch allure, with mvn clean test-compile failsafe:integration-test -P allure and then the run is succesful but empty results.

For some extra information:

`pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh ''
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn clean test-compile failsafe:integration-test -P allure' 
            }
            post {
                always {
                  allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
                }
            }
        }
    }
}`

![screen shot 2017-11-16 at 12 14 53](https://user-images.githubusercontent.com/25155117/32888521-cbd11a36-cac7-11e7-8519-5b21ba9f75fa.png)

**Comment by cyborghound** [comment]
Got it working already, thanks for your help!

Found one problem, the result page from Fitnesse does not appear because of a 404:

![screen shot 2017-11-16 at 15 21 56](https://user-images.githubusercontent.com/25155117/32895951-f9a4cc18-cae1-11e7-877a-100aaa181be3.png)

**Comment by fhoeben** [comment]
That 404 didn't happen when I tried it, as I recall. 
Can you look at the page source and see what URL is being used (and is not found)? The name index.html surprises me, I would expect a target <pagename>.html.

**Comment by tcnh** [comment]
That's strange... index.html should be something like ../../fitnesseResults/MyTestCaseName.html

Is the fitnesse-results directory copied into the allure-results folder? The listener copies that folder on the TestRunFinished event.

**Comment by cyborghound** [comment]
This is what I see:

This is the url: http://localhost:8080/job/FitnesseFramework/7/allure/data/attachments/78f9d467459b1728.html

This is from the inspector:
![screen shot 2017-11-16 at 15 55 10](https://user-images.githubusercontent.com/25155117/32897684-924190e2-cae6-11e7-8cb4-b5dc827d1565.png)

This is in my pom.xml
<img width="684" alt="screen shot 2017-11-16 at 15 56 06" src="https://user-images.githubusercontent.com/25155117/32897760-b6dd3cd0-cae6-11e7-91e7-d1a77d4f326e.png">

And this is the place I found in the Jenkins Workspace that I think should be loaded.
<img width="439" alt="screen shot 2017-11-16 at 15 58 45" src="https://user-images.githubusercontent.com/25155117/32897957-2937ddc6-cae7-11e7-86ba-53b3d64c9209.png">

This is my folder structure:
<img width="600" alt="screen shot 2017-11-16 at 16 13 44" src="https://user-images.githubusercontent.com/25155117/32898711-2b7b3fb8-cae9-11e7-88da-47de0c231df3.png">

**Comment by tcnh** [comment]
I'd expect them to be in target/allure-report/fitnesseResults (that's the default value of allure.report.directory.

Wait... you're not generating the report using mvn site but using the plugin. That means the copy-resources step is not executed (phase = site)

We create a 'wrapper html' containing an iframe pointing to the right location and attach that, not the actual result file (that would break all css/js of the fitnesse report). The fitnesse report files are copied to the report folder separately.

You could add a pipeline step that copies target/fitnesse-results/* to allure-report/fitnesse-results to get it running

**Comment by fhoeben** [comment]
That `iframe` does not seem to account for the error page you see, as it does not end with `index.html`? Can you check in that page (with the 404) where the `index.html` reference is?

**Comment by cyborghound** [comment]
I found this weird too. This is a screenshot from when I open the page and check the page source.

<img width="1359" alt="screen shot 2017-11-17 at 08 57 22" src="https://user-images.githubusercontent.com/25155117/32936675-84001668-cb75-11e7-9ec5-5bdfb42344c2.png">

It looks like the .html results from Fitnesse are not copied to the Allure destination, because the .html is correct, but there is no FitnesseResults folder. Is the resource location in the pom.xml the correct one? It shows the project workspace /fitnesse-results but they are in /target/fitnesse-results.

This is the screenshot from my allure-reports folder.

<img width="374" alt="screen shot 2017-11-17 at 09 16 16" src="https://user-images.githubusercontent.com/25155117/32937264-09a7a432-cb78-11e7-8fd6-b0caef34c7a5.png">

The url you see in my browser search field is from that build, and the files are in data/attachments/

I tried to change some paths but didn't get any results yet.

**Comment by cyborghound** [comment]
When I click on the this url in the iframe:

<img width="1359" alt="screen shot 2017-11-17 at 08 57 22" src="https://user-images.githubusercontent.com/25155117/32936675-84001668-cb75-11e7-9ec5-5bdfb42344c2.png">

Then I go to this page:

<img width="356" alt="screen shot 2017-11-20 at 08 23 14" src="https://user-images.githubusercontent.com/25155117/33006847-35faa4de-cdcc-11e7-862b-9d231aa03ccb.png">

Maby this helps? I think that this means the fitnesseResults folder is not there as you can see in my previous post. I don't know why, but the contents are nog copied to this folder.

**Comment by fhoeben** [comment]
Check @tcnh comment: since you are creating the report using a plugin (and not via Maven's 'site' phase) not all expected Maven steps are executed.

You have to either:
 * Configure Jenkins to do the copy for you (using a (post-) build step, or pipeline command)
 * Generate the report via maven commands, as described in the README, instead of via the Allure Jenkins plugin (and please note the readme states `<directory>${project.build.directory}/allure-results/fitnesseResults</directory>` which is different to what I see in the screenshot of your pom ('it has 'fitnesse-results' instead of 'allure-results')

**Comment by cyborghound** [comment]
Worked all out! The first problem was: `<directory>${project.build.directory}/allure-results/fitnesseResults</directory>`. When this was changed the content were copied over to the right folder.

And the other problem was the Allure plugin for Jenkins which is Allure2. I removed the plugin and used the in house HTML Publisher for attaching Allure to my project. It copies the content from target/allure-report/ to this HTML Publisher and shows my results when clicking on the button.

A problem I found is that the Content Security Policy for Jenkins blocks almost everything you want to show in the HTML Publisher, so I needed to start Jenkins with an empty CSP, and then it worked. Else nothing shows up. Thanks for the help guys!

**Comment by Unforgettable631** [comment]
@Blackpander, we were also struggling with the optimal CSP setting. What worked for us was:
`System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", 
                     "default-src 'self'; img-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';")`

You can temporarly try if this works for you via Jenkins > Script console.
Hope this helps to determine the CSP settings for your project.

There could also be a problem when opening the index.html in IE (blank page). This was caused by DocumentMode set to 7 or lower. Set it to 10 or Edge and there should be no problem opening and navigating in the Allure report.

**Comment by Blackpander** [comment]
Thanks @Unforgettable631 I will test around with this. @tcnh Do you know if it's possible to combine results into one report. So every HTML Publisher button goes to the same report but only all the reports are bundled into 1.
